name: sqflow_annotations
version: 1.0.0
description: >
  Annotation library for declarative SQL table and schema definitions in Dart.
  Designed to be used with code generators that produce SQL schemas,
  migrations, or runtime metadata.

repository: https://github.com/interdev7/sqflow_annotations
homepage: https://github.com/interdev7/sqflow_annotations
issues: https://github.com/interdev7/sqflow_annotations/issues

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
